ibm-openbmc/phosphor-dbus-interfaces

xyz/openbmc_project/Inventory/Decorator/Asset.interface.yaml
SubModel is used to identify network interface.
Signed-off-by: LuluTHSu <Lulu_Su@wistron.com>
=> asset: Add SubModel

gen/org/open_power/HardwareIsolation/Create/meson.build, gen/org/open_power/HardwareIsolation/meson.build, gen/org/open_power/meson.build, yaml/org/open_power/HardwareIsolation/Create.interface.yaml
The upstream patch for the same: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/44230.
=> HardwareIsolation: Added the "CreateWithEntityPath" method

gen/com/ibm/Host/Target/meson.build, gen/com/ibm/Host/meson.build, gen/com/ibm/meson.build
Some downstream changes don't pass CI. Fix that up with this commit.
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
=> pdi: adjust downstream code to pass CI

yaml/xyz/openbmc_project/Logging/Event.interface.yaml
Upstream Gerrit link:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/48274/4
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/48275/4
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/48277/4
=> Added the required D-Bus interfaces for the deconfigure reason feature

yaml/xyz/openbmc_project/Control/Power/Mode.interface.yaml
Add the ability to see when system is in safe mode.
=> Add safe mode to dbus

gen/com/ibm/Dump/Entry/SBE/meson.build, gen/com/ibm/Dump/Entry/meson.build, yaml/com/ibm/Dump/Create.interface.yaml, yaml/com/ibm/Dump/Entry/SBE.interface.yaml, yaml/com/ibm/VPD/Manager.interface.yaml, yaml/xyz/openbmc_project/Control/Power/Mode.interface.yaml
More ibm-openbmc patches that are needed in our 1050 branch.
=> 1050 downstream patches batch two

gen/com/ibm/ipzvpd/PSPD/meson.build, gen/com/ibm/ipzvpd/meson.build, yaml/com/ibm/ipzvpd/PSPD.interface.yaml
=> Addition of PSPD KW.

gen/xyz/openbmc_project/Software/LID/meson.build, gen/xyz/openbmc_project/Software/meson.build, yaml/xyz/openbmc_project/Software/LID.interface.yaml
This method will allow for validation to occur during inband code updates. It will ensure that the User Access Key, Signature, and Minimum Ship Level requirements are met before the update proceeds.
=> Create Validate interface for inband code update

gen/org/open_power/OCC/Device/meson.build, gen/org/open_power/OCC/meson.build, yaml/org/open_power/OCC/Device.errors.yaml, yaml/org/open_power/OCC/Device.metadata.yaml
```
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I91f1a459fecc623168f65a3b17ff50974344eec7
```
=> 1050: open_power: add OCC errors from openpower-occ-control

gen/com/ibm/Panel/Panel/meson.build, gen/com/ibm/Panel/meson.build, gen/com/ibm/meson.build, yaml/com/ibm/Panel/Panel.interface.yaml
Provides documentation on methods and properties present under com.ibm.panel interface hosted by com.ibm.PanelApp service.
=> Document the methods and properties under com.ibm.panel interface

yaml/xyz/openbmc_project/Control/Power/Mode.interface.yaml
Add new property that defines what Power Modes are supported.
Tested on Rainier.
'''
busctl -l introspect org.open_power.OCC.Control /xyz/openbmc_project/control/host0/power_mode
NAME                                   TYPE      SIGNATURE RESULT/VALUE                                                                                                                                                                                                                                                                                                                                                                                                                  FLAGS
...
xyz.openbmc_project.Control.Power.Mode interface -         - …
=> Control.Power.Mode: Add AllowedPowerModes property

yaml/xyz/openbmc_project/Control/Power/Mode.interface.yaml
New modes:
- Balanced Performance
- Efficiency Favor Performance
- Efficiency Favor Power Also reordered the enums (alphabetical)
Modes were added to the Redfish ComputerSystem v1.22 schema
Change-Id: I70ba36a6afb13896d812eeb822752020b03d9673
=> Control.Power.Mode: Add new power management modes

gen/com/ibm/License/Entry/LicenseEntry/meson.build, gen/com/ibm/License/Entry/meson.build, gen/com/ibm/License/LicenseManager/meson.build, gen/com/ibm/License/meson.build, gen/com/ibm/meson.build, yaml/com/ibm/License/Entry/LicenseEntry.interface.yaml, yaml/com/ibm/License/LicenseManager.interface.yaml
Rebasing License Manager 
This pull request will apply license manager related changes 
Tested by creating/flashing the image and making sure that license manager is up and running
Change-Id: I16d47ff42df86245a94a7e2fd6b729d66472ac2b
=> License Manager Rebase

yaml/com/ibm/ipzvpd/README.md, yaml/xyz/openbmc_project/Software/README.md
Something new was picked up by CI that has some minor formatting changes to some existing markdown files.
=> 1110: needed formatting changes to markdown files

gen/org/open_power/HardwareIsolation/Create/meson.build, gen/org/open_power/HardwareIsolation/meson.build, gen/org/open_power/meson.build, yaml/org/open_power/HardwareIsolation/Create.interface.yaml, yaml/xyz/openbmc_project/Logging/Event.interface.yaml
In this patch, added the Severity property with list of enumerations to indicate the severity of the event.
Change-Id: I477973b0a193f9e9384beed40df26959f5b27449
=> Logging: Event: Added the Severity property and Added the "CreateWithEntityPath" method 

.secrets.baseline, gen/xyz/openbmc_project/User/GoogleAuthenticator/meson.build, gen/xyz/openbmc_project/User/MFABypass/meson.build, gen/xyz/openbmc_project/User/MultiFactorAuthConfiguration/meson.build, gen/xyz/openbmc_project/User/meson.build, yaml/xyz/openbmc_project/User/GoogleAuthenticator.interface.yaml, yaml/xyz/openbmc_project/User/MFABypass.interface.yaml, yaml/xyz/openbmc_project/User/MultiFactorAuthConfiguration.interface.yaml
This commit  defines Multi-factor authentication  D-bus interfaces 
1. Google authenticator configuration D-bus interfaces 
2. Multi-factor authentication bypass D-bus interfaces
=> Add Multi-factor authentication D-bus interfaces 

yaml/xyz/openbmc_project/User/GoogleAuthenticator.interface.yaml, yaml/xyz/openbmc_project/User/MFABypass.interface.yaml, yaml/xyz/openbmc_project/User/MultiFactorAuthConfiguration.interface.yaml
This PR pulls latest D-bus patchset from upstream commits
https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/72602
=> Updated Multi-factor authentication D-bus interfaces

gen/com/google/gbmc/Hoth/meson.build, gen/com/google/gbmc/meson.build, gen/meson.build, gen/xyz/openbmc_project/Control/Host/meson.build, gen/xyz/openbmc_project/Control/meson.build, gen/xyz/openbmc_project/Dump/Create/meson.build, gen/xyz/openbmc_project/Dump/meson.build, gen/xyz/openbmc_project/Memory/MemoryECC/meson.build, gen/xyz/openbmc_project/Memory/meson.build, gen/xyz/openbmc_project/Nvme/Status/meson.build, gen/xyz/openbmc_project/Nvme/meson.build, gen/xyz/openbmc_project/Smbios/MDR_V2/meson.build, gen/xyz/openbmc_project/Smbios/meson.build, gen/xyz/openbmc_project/Software/Update/meson.build, gen/xyz/openbmc_project/Software/Version/meson.build, gen/xyz/openbmc_project/Software/meson.build, gen/xyz/openbmc_project/State/BMC/meson.build, gen/xyz/openbmc_project/State/Chassis/meson.build, gen/xyz/openbmc_project/State/Host/meson.build, gen/xyz/openbmc_project/State/meson.build
sdbusplus updated to version 9 and added a new file
=> meson file updates required due to sdbusplus updates

yaml/xyz/openbmc_project/User/Attributes.interface.yaml, yaml/xyz/openbmc_project/User/Manager.interface.yaml, yaml/xyz/openbmc_project/User/TOTPAuthenticator.interface.yaml
This commit pulls updated TOTP D-bus interfaces from upstream
=> Pull latest TOTP D-bus interfaces from upstream

yaml/xyz/openbmc_project/User/TOTPAuthenticator.interface.yaml
This reverts commit 956e8e349e94ba0679dd545e89c98220d6db911d.
=> Revert "TOTP: Add ClearSecretKey D-bus method"

yaml/com/ibm/ipzvpd/README.md, yaml/xyz/openbmc_project/Software/README.md
Something got updated in the container that now wants lines wrapped at 80 again.
=> 1110: fix CI formatting

.secrets.baseline, gen/xyz/openbmc_project/User/TOTPAuthenticatorManager/meson.build, gen/xyz/openbmc_project/User/meson.build, yaml/xyz/openbmc_project/User/TOTPAuthenticator.interface.yaml, yaml/xyz/openbmc_project/User/TOTPAuthenticatorManager.interface.yaml
This pull MFA D-bus interfaces from upstream 
1. Clear secret key D-bus interface 
2. Updated GenerateSecretKeyRequired D-bus interface
=> Add IsGenerateSecretKeyRequired D-bus method

gen/com/ibm/VPD/Collection/meson.build, gen/com/ibm/VPD/meson.build, yaml/com/ibm/VPD/Collection.interface.yaml
This commit implements com.ibm.VPD.Collection
interface which holds CollectionState property
to describe the status of FRU VPD collection.
=> Interface for FRU VPD collection

.secrets.baseline, yaml/xyz/openbmc_project/User/Attributes.interface.yaml, yaml/xyz/openbmc_project/User/Manager.interface.yaml
This commit updates GetUserInfo to return TOTPSecretkeyRequired
Change-Id: I6a37e65a9746b16947ad16f69d1bf459b8b8eeac
=> Update GetUserInfo to return TOTPSecretkeyRequired
