ibm-openbmc/phosphor-dbus-interfaces

xyz/openbmc_project/Control/Host/NMI.interface.yaml

https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/21770/
Add a new dbus interface to trigger NMI.
Signed-off-by: Lakshminarayana R. Kammath <lkammath@in.ibm.com>
Change-Id: I81f61fbbba757bff2d99585ca0e22816483c7c37

Add a new dbus interface to trigger NMI.

---

xyz/openbmc_project/State/Shutdown/Power.errors.yaml

Already in master.  Needed by code in phosphor-state-manager.

Add Blackout error to OP940

---

xyz/openbmc_project/Network/EthernetInterface.interface.yaml

The validation for Nameservers property was added a part of
below commit.
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-networkd/+/24601/
The idea behind this commit is to support the Validation failure,
where we catch the InvalidArgument error, so that Network service
wont be crashed.
TestedBy:
PATCH operation on Nameservers property using some random junk values
and made sure that , the backend throws an error without the Network
service being crashed.
Signed-off-by: Manojkiran Eda <manojkiran.eda@gmail.com>
Change-Id: I4233a1ea69714825da51bc9def13d79047f1f02d

Adding Invalid Argument Error for Nameservers property

---

xyz/openbmc_project/Network/EthernetInterface.interface.yaml

Systemd.network allows fallback option for LinkLocalAddressing
If "fallback" or "ipv4-fallback" is specified, then an IPv4
link-local address is configured only when DHCPv4 fails.
If "fallback", an IPv6 link-local address is always configured.
Signed-off-by: Ravi Teja <raviteja28031990@gmail.com>
Change-Id: I2bff8ae4f147426210752eeddbe85a54d69b3c8e

Network: add fallback option for LinkLocalAddressing property

---

xyz/openbmc_project/Network/EthernetInterface.interface.yaml

Linklocal fallback is not working in op940, so reverting fallback option changes

Revert linklocal fallback option

---

gen/com/ibm/License/Entry/LicenseEntry/meson.build
gen/com/ibm/License/Entry/meson.build
gen/com/ibm/License/LicenseManager/meson.build
gen/com/ibm/License/meson.build
gen/com/ibm/meson.build
yaml/com/ibm/License/Entry/LicenseEntry.interface.yaml
yaml/com/ibm/License/LicenseManager.interface.yaml
yaml/xyz/openbmc_project/State/Decorator/PowerState.interface.yaml

This commit defines License Manager interface to support new license upload
and defines license entry interfaces to represent license objects
Licenses are objects representing application layer features. This is a one
to one relation ship. These objects have state and other properties to
represent each feature attributes
Signed-off-by: Sunitha Harish <sunharis@in.ibm.com>

Capacity-On-Demand: License manager DBus

---

yaml/org/open_power/OCC/PassThrough.interface.yaml

This will allow BMC root users to set any Power Modes including OEM modes
that are not available via Redfish.
Tested on Raininer and Everest systems
Change-Id: I5dd6be67120ab14caa1b3a972eb2571e3c821f7d
Signed-off-by: Chris Cain <cjcain@us.ibm.com># When applied, this commit will… (max 50 col)::::

Add setMode method to OCC PassThrough interface

---

yaml/xyz/openbmc_project/State/BMC.interface.yaml
yaml/xyz/openbmc_project/State/Chassis.interface.yaml

This consists of 2 merged upstream commits:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/48692
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/48387
These are needed for APR functions

1020 power recovery

---

yaml/com/ibm/VPD.errors.yaml

DevTree gets selected based on HW and IM of the system VPD.
If we get anything unexpected from these keywords, it couldn't
determine which systemType it is and so shouldn't load DevTree.
A PEL with this error interface UnknownSystemType will be logged
and break the booting process there itself.
Signed-off-by: Alpana Kumari <alpankum@in.ibm.com>
Change-Id: I0437f4db87b4ab556d7c5433a861689c682fafe4

VPD Error interface UnknownSystemType supported

---

yaml/com/ibm/Dump/Entry/Resource.interface.yaml

Add new property in the resource dump entry for storing the
response code  returned by the host after requesting a new
resource dump.
Signed-off-by: Dhruvaraj Subhashchandran <dhruvaraj@in.ibm.com>
Change-Id: I55a4de4e2b77c0387fba7412c122c28e9acdde7b

com-ibm-dump: Add response code to resource dump entry

---

gen/xyz/openbmc_project/Inventory/Decorator/Slot/meson.build
gen/xyz/openbmc_project/Inventory/Decorator/meson.build
yaml/xyz/openbmc_project/Inventory/Decorator/Slot.interface.yaml

This interface provides a slot number property for an inventory item.
The initial use case is to hang this on certain
phosphor-inventory-manager paths so that when entity-manager probes on
them it can have $SlotNumber available as a variable to give a stable
sensor name, such as 'PCIe Card $SlotNumber Temp'.
Without this, if say the $index variable is used instead, and then there
is no guarantee which device will have which sensor name, especially for
cards that can be added in any order when the BMC is running.
Stable sensor names are important in the
phosphor-inventory-manager/entity-manager hybrid model where PIM is used
for inventory and EM is just used for config.
There is a LocationCode property already that could possibly be used on
some systems, but on IBM systems at least it …

inventory.decorator: Add slot number interface

---

gen/xyz/openbmc_project/State/Decorator/PowerSystemInputs/meson.build
gen/xyz/openbmc_project/State/Decorator/meson.build
yaml/xyz/openbmc_project/State/Decorator/PowerSystemInputs.interface.yaml

```
Add a new PowerSystemInputs interface to describe the state of the power
supplied to the chassis via the power supply unit(s), in order to have
state manager handle Brownout conditions as described in design doc:
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/48015
This interface would be implemented by the phosphor-power repo and the
Status property set to Fault when a Brownout condition is detected.
Change-Id: I7aeea45f7285835fdb97a34706b3eef610d7532d
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>
```

1020: State: New PowerSystemInputs interface

---

yaml/xyz/openbmc_project/Object/Delete.interface.yaml

```
- The object may not be allowed to delete due to insufficient permission
for example, the object might be created by the system, and the user
may not have permission to delete it.
Signed-off-by: Ramesh Iyyar <rameshi1@in.ibm.com>
Change-Id: Ib662bc275cb091ec41b701faa9aad65b2ae6c6fc
```

1020: Delete: Add InsufficientPermission error

---

gen/com/ibm/PLDM/PCIeTopology/meson.build
gen/com/ibm/PLDM/meson.build
gen/com/ibm/meson.build
yaml/com/ibm/PLDM/PCIeTopology.interface.yaml

This commit defines PCIeTopology DBus interface.
this interface is used by applications on bmc to
request the pcie topology information.
Signed-off-by: Pavithra Barithaya <pavithra.b@ibm.com>

Topology: PCIeTopology DBus

---

yaml/org/open_power/Logging/PEL.interface.yaml

This method returns a PEL in JSON format so it can be returned in
Redfish via an OEM attachment.
It's a method and not a property on the PEL.Entry interface because it
is fairly slow and it would bog down GetManagedObjects calls that don't
care about it.
Cherry picking master and fixing up the formatting of the YAML since it's different between master and ibm-openbmc now.
Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: I6d04cd4e301980f95736c05dd5e5b027d400d49b

openpower: Add GetPELJSON method

---

yaml/xyz/openbmc_project/Software/Version.errors.yaml
yaml/xyz/openbmc_project/Software/Version.metadata.yaml

This commit adds a InvalidSignature error to the
Software Version interface. It will ensure that
if the error is hit during the verification of
an image, a corresponding error is available to the
user. This will replace the InternalError that the
signature verification currently creates if it
fails.
This commit will also add a ExpiredAccessKey error
to the Software Version interface. It will provide the
user not only with a more specific error, but metadata
indicating the direct cause. This will also replace an
InternalError that the Update Access Key verifier creates
when the criteria is not met.

Add Error to Software Version Interface

---

yaml/xyz/openbmc_project/Control/Power/Cap.interface.yaml

The power cap properties are hosted by Settings. The values need to be
written by OCC.Control service. When occ-control attempts to write
these properties, it gets an error because the values are not writable.
Change-Id: I72ac24ac91ab3fd050a9305a6a07eab96ee7e88b
Signed-off-by: Chris Cain <cjcain@us.ibm.com>

Change power cap bounds to be writable

---

yaml/xyz/openbmc_project/Inventory/Item/PCIeDevice.interface.yaml

The commit adds property "LanesInUse" property for PICeDevice
interface.
It will denote the number of PCIe lanes in use by this device.
Signed-off-by: Sunny Srivastava <sunnsr25@in.ibm.com>
Change-Id: If3d1bca4ce8f186391d842e6b6884f8b898aeec0

Lanes in use property added

---

yaml/xyz/openbmc_project/Inventory/Item/PCIeSlot.interface.yaml

The commit adds property BusId to PCIeSlot interfce, the
property will be required to detect the bus on which the
slot resides.
Signed-off-by: Sunny Srivastava <sunnsr25@in.ibm.com>
Change-Id: I4709610c0882dd1f022011ed3f96031d5d853b46

BusId property in PCIeSlot interface

---

yaml/xyz/openbmc_project/Inventory/Item/Cable.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/Chassis.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/Connector.interface.yaml

This commit adds a new enum property called CableStatus
under the Cable Interface.
This also adds the downstream chassis_associations and connector associations.
Signed-off-by: Pavithra Barithaya <pavithra.b@ibm.com>

Add support for CableStatus property

---

yaml/xyz/openbmc_project/Inventory/Item/PCIeDevice.interface.yaml

The commit changes the type and default value for property
LanesInUse in order to accommodate the situation where reason
of not getting this value is unknown.
Signed-off-by: Sunny Srivastava <sunnsr25@in.ibm.com>
Change-Id: If3bccd89382934f4bcf7ccf16f8068153d113d2c

Default LanesInUse value to int64

---

yaml/com/ibm/Dump/Entry/Resource.interface.yaml

An initial value is missing in the host response codes
so adding 'Requested' as the initial value.
Signed-off-by: Dhruvaraj Subhashchandran <dhruvaraj@in.ibm.com>
Change-Id: I62c96704c58a6b2154ffbc6498625967cc1b9ca2

com-ibm-dump: Add initial value to response code

---

yaml/xyz/openbmc_project/Inventory/Manager.interface.yaml

Add uint16_t and array[string] as variant types for
Notify method
Defect:SW550463
Signed-off-by: Sagar Srinivas <sagar.srinivas@ibm.com>

Add additional variant types for Notify D-Bus method

---

yaml/xyz/openbmc_project/Network/EthernetInterface.interface.yaml

The existing D-Bus DHCPConf enumearation values do not allow IPv6
Stateless DHCP to be assigned. The IPv4 entries are sufficient, as
DHCP for the v4 stack is truly a boolean.
IPv6 is, at minimum, a ternary control. Adding new enumerations allows
the IPv6 configruation to be done in a more abstract fashion than the
current IPv6AcceptRA D-Bus entry. This D-Bus entry is a direct
reflection of how systemd-networkd manages Routint Advertisement, and
by extension DHCPv6. Only phosphor-network needs this knowledge.
Tested:
The changes compile.
Also, in combination with changes made to phosphor-network, many
busctl set/get property commands were issued to confirm the
enumerations were performing as expected.
Change-Id: I42a46549fed8b2d2187ea6a7eb7278c63b84bbef
Signed-off-by: Johnathan Mantey …

Add additional DHCP configuration options

---

yaml/xyz/openbmc_project/Control/Power/Mode.interface.yaml

The power mode state can be locked such that it cannot be changed. Two
methods are provided. One method is for locking the mode and another for
querying the current state of the lock.
Signed-off-by: Ben Tyner <ben.tyner@ibm.com>

Power mode state lock support

---

yaml/org/open_power/HardwareIsolation/Create.interface.yaml

The sdbus++ tool allows the YAML to specify either "path" or "object_path".  Switch to "object_path" everywhere for consistency and clarity.
Change-Id: Id83fe5bc1b6c803eb2fc554c8d3353ec7f4e4744
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>

treewide: use more specific object_path type

---

gen/com/ibm/Control/Host/PCIeLink/meson.build
gen/com/ibm/Control/Host/meson.build
gen/com/ibm/Control/meson.build
gen/com/ibm/PLDM/PCIeTopology/meson.build
gen/com/ibm/PLDM/meson.build
gen/com/ibm/meson.build
yaml/com/ibm/Control/Host/PCIeLink.interface.yaml
yaml/com/ibm/PCIeTopology.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/Cable.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/Chassis.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/Connector.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/PCIeDevice.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/PCIeSlot.interface.yaml

This commit
- adds support for com.ibm.Control.Host.PcieLink
interface that hosts a new boolean property called linkReset.
- defines PCIeTopology DBus interface.
This interface is used by applications on bmc to
request the pcie topology information.
- defines new enum property called CableStatus under the Cable Interface.
This also adds the downstream chassis_associations and
connector associations.
- changes the type and default value for property
LanesInUse in order to accommodate the situation where reason
of not getting this value is unknown.
- defines property to hold PCIe link status value
for a given PCIe slot.
- adds property BusId to PCIeSlot interfce, the
property will be required to detect the bus on which the
slot resides.
Signed-off-by: Pavithra Barithaya <pavithra.b@ibm.com>

PCIeLink and PCIeTopology DBus Interfaces

---

yaml/xyz/openbmc_project/Inventory/Manager.interface.yaml

Add uint16_t and array[string] as variant types for Notify method
Defect:SW550463
Signed-off-by: Sagar Srinivas <sagar.srinivas@ibm.com>

Add additional variant types for Notify D-Bus method (#59)

---

yaml/org/open_power/Logging/PEL/Entry.interface.yaml

Expose four more PEL (IBM's event log format) fields on D-Bus so they are available for other applications.
Change-Id: I9cf752fadf6dfff892652dc02a55b93794b81ede

ibm: Add new properties to Logging.PEL.Entry interface

---

yaml/xyz/openbmc_project/Software/LID.interface.yaml

This method is invoked during in-band code update path to assemble all the lids and create a code update image tar ball.

Assemble code update image method

---

gen/com/ibm/ipzvpd/VSBK/meson.build
gen/com/ibm/ipzvpd/meson.build
yaml/com/ibm/ipzvpd/VSBK.interface.yaml

This commit will add interface to support the new record(VSBK) and its keywords to store the system backplane's critical data as backup.
The Bonnell BMC is embedded in the system backplane, so if either fails, the backplane should be replaced as a whole. Thus, we must backup the system backplane critical keywords on the VSBK record on the operator panel base EEPROM. Hence VSBK interface being added.
Below is the introspect for VSBK:
busctl introspect xyz.openbmc_project.Inventory.Manager /xyz/openbmc_project/inventory/system/chassis/motherboard/ base_op_panel_blyth com.ibm.ipzvpd.VSBK
NAME                TYPE      SIGNATURE RESULT/VALUE                             FLAGS
.BR                 property  ay        2 83 48                                  emits-change writable
.D0 …

Add a new interface for VSBK record 

---

gen/xyz/openbmc_project/Network/StaticRoute/Create/meson.build
gen/xyz/openbmc_project/Network/StaticRoute/meson.build
yaml/xyz/openbmc_project/Network/StaticRoute.interface.yaml
yaml/xyz/openbmc_project/Network/StaticRoute/Create.interface.yaml

Static routing provides the network administrator with full control over the routing behavior of the BMC network.
This commit adds static route d-bus interface and properties required.
Change-Id: Ib6abea1a9ce2f55cb54489c334b0072bf4fb726e

Add Network Static Route D-bus Interface

---

yaml/xyz/openbmc_project/State/Chassis.errors.yaml
yaml/xyz/openbmc_project/State/Chassis.interface.yaml
yaml/xyz/openbmc_project/State/Host.errors.yaml
yaml/xyz/openbmc_project/State/Host.interface.yaml

Two merged commits from upstream:
- https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/63742
- https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/63758

1050 bmc notready errors

---

yaml/xyz/openbmc_project/Network/Client.interface.yaml

```
Add TCP/UDP transport protocol for Client interface to make it use for
different applications like rsyslog as example.
Change-Id: I08511a1a70396e1c6fb979febfa8fb7343235e9d
Signed-off-by: Ivan Mikhaylov <fr0st61te@gmail.com>
```

1050: network/client: add TCP/UDP as Transport Protocol for Client

---

gen/xyz/openbmc_project/Logging/AuditLog/meson.build
gen/xyz/openbmc_project/Logging/meson.build
yaml/xyz/openbmc_project/Logging/AuditLog.interface.yaml

Scaled down implementation of upstream design still under review [1].
Upstream PDI changes also still under review [2].
Provides two methods:
- GetAuditLog: Return limited number of entries sorted newest to
oldest.
- GetLatestEntries: Create downloadable file containing all entries
sorted oldest to newest.
It is expected upstream that a full file download of the audit log
entries won't be accepted. Therefore the methods are split downstream to
simplify rework on upstream merge.
[1] https://gerrit.openbmc.org/c/openbmc/docs/+/63915
[2] https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/66616

Audit Log: Add xyz.openbmc_project.logging.AuditLog

---

yaml/xyz/openbmc_project/Network/SystemConfiguration.interface.yaml

Hostname does not allow special characters while setting hostname this commit adds InvalidArgument error to handle invalid hostnames
Change-Id: I2ecc92637364baebe9e845bd22099fcb9744c2f4

Add Hostname property errors

---

gen/xyz/openbmc_project/Certs/ACF/meson.build
gen/xyz/openbmc_project/Certs/meson.build
yaml/xyz/openbmc_project/Certs/ACF.interface.yaml

Methods added to interface are InstallACF and GetACFInfo This is functionality to install an ibm-acf file onto the system This interface is intended to be used by bmcweb.
InstallACF method is to install the ACF onto the system which
returns info about said file. Passing empty data to this
method will uninstall the file.
GetACFInfo method returns the ACF contents, expiration date
of the acf file, and if it is installed.

ACF interface added

---

yaml/xyz/openbmc_project/Logging/AuditLog.interface.yaml

Implementation of method GetLatestEntries() in phosphor-logging resulted in allowing 0 to be specified for maxCount. Updating description to match the implementation.

Audit Log: Update GetLatestEntries description

---

gen/xyz/openbmc_project/Logging/AuditLog/meson.build
gen/xyz/openbmc_project/Logging/meson.build
yaml/xyz/openbmc_project/Logging/AuditLog.interface.yaml

Scaled down implementation of upstream design still under review [1]. Upstream PDI changes also still under review [2].
Provides two methods:
- GetAuditLog: Return limited number of entries sorted newest to oldest.
- GetLatestEntries: Create downloadable file containing all entries sorted oldest to newest.
It is expected upstream that a full file download of the audit log entries won't be accepted. Therefore the methods are split downstream to simplify rework on upstream merge.
[1] https://gerrit.openbmc.org/c/openbmc/docs/+/63915
[2] https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/66616
Also includes commit:
- Audit Log: Update GetLatestEntries description (#99)

Audit Log: Add xyz.openbmc_project.logging.AuditLog (#95)

---

yaml/com/ibm/ipzvpd/VSBK.interface.yaml

Add keywords missing in VSBK YAML
Test:
busctl introspect xyz.openbmc_project.Inventory.Manager
/xyz/openbmc_project/inventory/system/chassis/motherboard/
base_op_panel_blyth
Displays all the keywords documented in this YAML file.

1060:Add keywords missing in VSBK YAML

---

yaml/com/ibm/ipzvpd/VSBK.interface.yaml

```
Test:
busctl introspect xyz.openbmc_project.Inventory.Manager
/xyz/openbmc_project/inventory/system/chassis/motherboard/
base_op_panel_blyth
Displays all the keywords documented in this YAML file.
Signed-off-by: Priyanga Ramasamy <priyanga24@in.ibm.com>
```

1050: Add keywords missing in VSBK YAML (#105)

---

.secrets.baseline

This creates a baseline file (and initial responses to any potential secrets found).
After this file is merged, all CI jobs after will run the detect-secrets tool against incoming commits to verify no potential secrets are being shared. If one is found, CI will fail until the .secrets.baseline is updated for the new issue.
See the following for more info:
https://github.com/IBM/detect-secrets

1110:CI-only: create detect-secrets baseline file

---

yaml/xyz/openbmc_project/Inventory/Item/Cable.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/Chassis.interface.yaml

This documentation is useful for user interface applications such as redfish to traverse to what they are connected to add associations.
Signed-off-by: Pavithra Barithaya <pavithrabarithaya07@gmail.com>

Cable, Chassis: Add associations documentation

---

yaml/xyz/openbmc_project/Inventory/Item/Cable.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/Connector.interface.yaml

This documentation is useful for user interface applications such as redfish to traverse to what they are connected to add associations.
Change-Id: I71728d654c00ada25359c95de8b368e7a3c66283
Signed-off-by: Pavithra Barithaya <pavithrabarithaya07@gmail.com>

Cable, Connector: Add associations documentation

---

gen/xyz/openbmc_project/Software/MinimumVersion/meson.build
gen/xyz/openbmc_project/Software/meson.build
yaml/xyz/openbmc_project/Software/MinimumVersion.interface.yaml

The minimum version is an optional meson option (bmc-msl)[1] that prevents firmware updates to a level lower than the one set via this option.
The error logged is a Software Incompatible[2] error.
Add the minimum version as a property of a new interface. This will be populated by the code updater app. It can then be mapped to the SoftwareInventory LowestSupportedVersion Redfish property and be available to the user via Redfish and the GUI so that the user can know in advance which version of software is not supported on their system and avoid having to debug a code update failure after they attempt to install an incompatible version.
```
1: https://github.com/openbmc/phosphor-bmc-code-mgmt/blob/85c71a13e0938cc4d36caf6b8e735e9740b2e351/meson.options#L100
2: …
```

1030: software: Add Minimum Version interface

---

gen/xyz/openbmc_project/Software/MinimumVersion/meson.build
gen/xyz/openbmc_project/Software/meson.build
yaml/xyz/openbmc_project/Software/MinimumVersion.interface.yaml

The minimum version is an optional meson option (bmc-msl)[1] that prevents firmware updates to a level lower than the one set via this option.
The error logged is a Software Incompatible[2] error.
Add the minimum version as a property of a new interface. This will be populated by the code updater app. It can then be mapped to the SoftwareInventory LowestSupportedVersion Redfish property and be available to the user via Redfish and the GUI so that the user can know in advance which version of software is not supported on their system and avoid having to debug a code update failure after they attempt to install an incompatible version.
```
1: https://github.com/openbmc/phosphor-bmc-code-mgmt/blob/85c71a13e0938cc4d36caf6b8e735e9740b2e351/meson.options#L100
2: …
```

1050: software: Add Minimum Version interface

---

gen/xyz/openbmc_project/Software/MinimumVersion/meson.build
gen/xyz/openbmc_project/Software/meson.build
yaml/xyz/openbmc_project/Software/MinimumVersion.interface.yaml

The minimum version is an optional meson option (bmc-msl)[1] that prevents firmware updates to a level lower than the one set via this option.
The error logged is a Software Incompatible[2] error.
Add the minimum version as a property of a new interface. This will be populated by the code updater app. It can then be mapped to the SoftwareInventory LowestSupportedVersion Redfish property and be available to the user via Redfish and the GUI so that the user can know in advance which version of software is not supported on their system and avoid having to debug a code update failure after they attempt to install an incompatible version.
```
1: https://github.com/openbmc/phosphor-bmc-code-mgmt/blob/85c71a13e0938cc4d36caf6b8e735e9740b2e351/meson.options#L100
2: …
```

1060: software: Add Minimum Version interface

---

gen/xyz/openbmc_project/Software/MinimumVersion/meson.build
gen/xyz/openbmc_project/Software/meson.build
yaml/xyz/openbmc_project/Software/MinimumVersion.interface.yaml

The minimum version is an optional meson option (bmc-msl)[1] that prevents firmware updates to a level lower than the one set via this option.
The error logged is a Software Incompatible[2] error.
Add the minimum version as a property of a new interface. This will be populated by the code updater app. It can then be mapped to the SoftwareInventory LowestSupportedVersion Redfish property and be available to the user via Redfish and the GUI so that the user can know in advance which version of software is not supported on their system and avoid having to debug a code update failure after they attempt to install an incompatible version.
```
1: https://github.com/openbmc/phosphor-bmc-code-mgmt/blob/85c71a13e0938cc4d36caf6b8e735e9740b2e351/meson.options#L100
2: …
```

1110: software: Add Minimum Version interface

---

yaml/com/ibm/Dump/Entry/Hardware.interface.yaml
yaml/com/ibm/Dump/Entry/Hostboot.interface.yaml
yaml/com/ibm/Dump/Entry/Resource.interface.yaml
yaml/com/ibm/Dump/Entry/SBE.interface.yaml

Following commits are merged in master needed in 1110
51107: com-ibm-dump: Add response code to resource dump entry | https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/51107
71273: com.ibm: Add UserChallenge to replace password | https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/71273
71102: com.ibm: Add additional properties to hardware dump | https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/71102
71103: com.ibm: Add additional properties to SBE dump | https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/71103
71104: com.ibm: Add ErrorLogId to Hostboot dump | https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/71104

Pulling OpenPOWER dump interfaces from master

---

yaml/com/ibm/Dump/Create.interface.yaml

The Self Boot Engine (SBE) is contained on certain memory buffers. When the SBE becomes unresponsive due to hardware or software issues, there's a need to collect diagnostic dumps from it. To address this need and differentiate such dumps from others, this commit adds the `MemoryBufferSBE` type to the com.ibm.Dump.Create interface. The structure and input to collect this dump is different from the processor SBE dump so making it a new dump type.
Change-Id: Ib07a0caa1521c5ae5f6e0682029b5c9e497152e8

com.ibm: Add MemoryBufferSBE dump type

---

gen/com/ibm/VPD/FRUManager/meson.build
gen/com/ibm/VPD/meson.build
yaml/com/ibm/VPD/FRUManager.interface.yaml

This commit adds yaml file that defines interfaces for VPD Manager
Defines the following interfaces:-
-Interface to update the value of a given keyword
-Interafce to read the value of a given keyword
-Interface to collect VPD of a particular FRU
-Interface to delete FRU VPD
-Interface to get the location code of a particular FRU
-Interface for VPD collection status

Add yaml file for VPD Manager interface

---

yaml/com/ibm/ipzvpd/README.md
yaml/com/ibm/ipzvpd/VINI.interface.yaml
yaml/xyz/openbmc_project/Software/README.md

The property DI reflects keyword required to hold DRAM manufacturer ID in case of DIMMs.
Change-Id: I197d13a006ad9bad5225d951b730cca57c263749

com.ibm: Add DI property to ipzvpd VINI interface

---

yaml/xyz/openbmc_project/Network/StaticGateway.interface.yaml
yaml/xyz/openbmc_project/Network/StaticGateway/Create.interface.yaml

Static gateway configuration does not require prefix length property
This commit removes PrefixLength property from static gateway D-bus method and interface.
Change-Id: Ic21bfdc457bfba2bfd9993bb786c084641e8ffe3

StaticGateway: Remove PrefixLength property

---

xyz/openbmc_project/Control/TPM/Policy.interface.yaml

IBM has a new requirement to use a new sensor (disable_tpm_sensor) to disable TPM for P9.
This commit adds a new interface to the PDI repository for disabling TPM called TPMDisable.
issue: https://github.com/ibm-openbmc/dev/issues/3634

Add TPMDisable interface

---

gen/com/ibm/PLDM/ChapData/meson.build
gen/com/ibm/PLDM/meson.build
gen/com/ibm/meson.build
yaml/com/ibm/PLDM/ChapData.interface.yaml

Adding ChapName and ChapSecret properties in PLDM to transfer ChapData information between PLDM and Host as part of 1KW line item. This Chap data is a information of encrypted password which would be set by GUI into Dbus properties via redfish.
PLDM is hosting these properties into the Dbus path and when GUI changes properties values then PLDM will collect that data and sends that data to Host using FILEIO operation.
>chap properties are seen at Dbus level like this:
`root@rainxxxbmc:~# busctl introspect  xyz.openbmc_project.PLDM /xyz/openbmc_project/pldm
NAME                                       TYPE      SIGNATURE RESULT/VALUE                             FLAGS
com.ibm.PLDM.ChapData                      interface -         -                                        -
.ChapName …

Adding chapdata properties support for fileio operation

---

gen/xyz/openbmc_project/State/BMC/Redundancy/meson.build
gen/xyz/openbmc_project/State/BMC/meson.build
yaml/xyz/openbmc_project/State/BMC/Redundancy.interface.yaml

Define an interface in support of redundant BMC functionality as mentioned in the design doc
https://gerrit.openbmc.org/c/openbmc/docs/+/70233.  To start with, it defines the Role and RedundancyEnabled properties.
With this usage one BMC is considered the active BMC, and the other is the passive.  There will be a new application running on each BMC that hosts this interface.
This implementation is not related to the one that uses the xyz.openbmc_project.State.BMCRedundancy interface, of which there doesn't appear to be any upstream uses of.
Change-Id: I6415175bbee03f6c07b14e1db1ee0082bd1724ed

State: Add BMC redundancy interface

---

.secrets.baseline
gen/xyz/openbmc_project/State/BMC/Redundancy/Sibling/meson.build
gen/xyz/openbmc_project/State/BMC/Redundancy/meson.build
yaml/xyz/openbmc_project/State/BMC/Redundancy/Sibling.interface.yaml

The redundant BMC design at
https://gerrit.openbmc.org/c/openbmc/docs/+/70233 describes creating two new applications: one to do the management, and another to provide an API that the first application uses to get information from the sibling BMC.  This commit is the D-Bus interface of the latter daemon.
Change-Id: I0cd3d2f78ffbfc2998e7c8fcace1723954df3e98

State: Add Redundant BMC Sibling interface

---

gen/com/ibm/Host/Target/meson.build
gen/com/ibm/Host/meson.build
gen/com/ibm/meson.build
yaml/com/ibm/Host/Target.interface.yaml

```
This commit adds interface to choose the OS.
This property reflects the user settings and not a status.
It is possible that the user can change the setting
at any point of time. But the property will be applied
only when the host boots the next time.
The interface is contained within com.ibm.Host namespace.
Signed-off-by: Pavithra Barithaya <pbaritha@in.ibm.com>
Signed-off-by: Deepak Kodihalli <dkodihal@in.ibm.com>
```

1110: Dual-boot: BIOS attribute for choosing OS

---

yaml/xyz/openbmc_project/Logging/Entry.interface.yaml

```
Add the error 'xyz.openbmc_project.Common.Error.Unavailable' to the
'Resolved' property of the Entry interface.
This change helps in notifying the users when the attempt to set the
Resolved property is prevented until the corresponding error log is
addressed.
For example, if the error log is associated with a HardwareIsolation
entry (which indicates the faulty hardware) and has not been resolved
yet; in this case, we need to prevent setting the 'Resolved' flag.
Change-Id: I64da52e572ba33f888d33039ac604c57b86d84de
Signed-off-by: Arya K Padman <aryakpadman@gmail.com>
```

1110: Logging: Entry: Add errors to Resolved Property

---

yaml/xyz/openbmc_project/HardwareIsolation/Entry.interface.yaml

The system may have additional spare hardware that is not currently configured.
When a configured component becomes isolated due to an error, an available spare can be activated without affecting user experience. This helps maintain the integrity of the system configuration.
This commit introduces a new enum to indicate that the hardware is currently isolated, but a spare has been activated, allowing the user to disregard this isolation.

HardwareIsolation: Implement new guard type: Spare

---

yaml/xyz/openbmc_project/Logging/Create.interface.yaml

When a daemon creates an event or error entry it is sometimes helpful to be able to look up that entry later, for example to mark it as resolved.  Add a return to the method call for this.
Change-Id: Ia010e53fda55cef8b9cfc948482e133f20040320

Logging.Create: return result path from create call

---

yaml/xyz/openbmc_project/User/TOTPAuthenticator.interface.yaml

This commit adds IsGenerateSecretekeyRequired() D-bus method This D-bus method identifies whether TOTP secret key setup required for a given user.
Change-Id: I5dbc5d2091b8d8f97295ffceec1b29cc94b85aed

Add IsGenerateSecretKeyRequired D-bus method

---

yaml/xyz/openbmc_project/Inventory/Item/Cable.interface.yaml
yaml/xyz/openbmc_project/Inventory/Item/PCIeSlot.interface.yaml

This commit-
- defines new enum property called CableStatus under the Cable Interface.
- defines property to hold PCIe link status value for a given PCIe slot.
- adds property BusId to PCIeSlot interfce, the property will be required to detect the bus on which the slot resides.
Change-Id: Id9b785e2971c8cd9a05e5bdac81f36f6bbd3f102
Signed-off-by: Pavithra Barithaya <pavithrabarithaya07@gmail.com>

PCIeLink and Cable Status DBus Interface

---

yaml/xyz/openbmc_project/Network/EthernetInterface.interface.yaml

The Link Layer Discovery Protocol (LLDP) is a vendor-neutral link layer protocol used by network devices for advertising their identity, capabilities, and neighbors on a local area network based on IEEE 802
This commit adds D-bus properties to control LLDP on ethernet interfaces
Systemd-network supports
[1] https://www.freedesktop.org/software/systemd/man/latest/systemd.network.html#EmitLLDP=
Change-Id: Iacd411c7d89367a6e3c7a546e71c59817d3fe970

Network: Add LLDP support on ethernet interfaces

---

gen/xyz/openbmc_project/DataSync/BMCData/meson.build
gen/xyz/openbmc_project/DataSync/meson.build
gen/xyz/openbmc_project/meson.build
yaml/xyz/openbmc_project/DataSync/BMCData.interface.yaml

- Introduced a new interface, "BMCData," to facilitate syncing BMC data between redundant BMC systems, as outlined in the following design document, https://gerrit.openbmc.org/c/openbmc/docs/+/71039.
- This interface can be implemented by application to enable data synchronization services in redundant BMC setups.
- The interface is started with an object path to allow application to host and manage data sync services.

DataSync: Added the "BMCData" interface

---

yaml/xyz/openbmc_project/State/BMC/Redundancy.interface.yaml

This property is used to manually disable redundancy, for use in at least testing and manufacturing environments.
Change-Id: I7073532c1de5cf17b045ce09ba58f395c2d408f8

State: Add DisableRedundancyOverride property

---

yaml/com/ibm/VPD/FRUManager.interface.yaml

This commit defines an API to update the keyword's value only on hardware.

API to Write Keyword on Hardware

---

yaml/xyz/openbmc_project/State/BMC/Redundancy.interface.yaml

When redundancy is enabled, there may be periods when fail overs are not allowed, such as in the middle of a code update.  The syncing of files between BMCs is still active during this time.  This property represents that.
Change-Id: I713cefad67298e62a03596654a0629cc60fb4caa

State: Add RBMC FailoversPaused property

---

gen/xyz/openbmc_project/Sensor/Purpose/meson.build
gen/xyz/openbmc_project/Sensor/meson.build
yaml/xyz/openbmc_project/Sensor/Purpose.interface.yaml

A chassis can have a sensor which tracks the total power consumption. Clients such as bmcweb need a programmatic approach to finding the unique sensor from the chassis.
A design discussion [1] in development channel of Discord settled on the following approach:
- Define a D-Bus interface for defining a special purpose for a sensor.
- Use the existing all_sensors/chassis association to connect the sensor to its Chassis.
- Clients such as bmcweb use object mapper to find all_sensors associated with the Chassis. They then filter to find the sensor implementing the specific purpose required.
This initial implementation only defines a single special purpose. The expectation is others will be added as needed in the future.
The openpower-occ-control repo implemented a total_power association.[2] …

Add new interface to define sensor purpose

---

gen/xyz/openbmc_project/Control/SyncBMCData/meson.build
gen/xyz/openbmc_project/Control/meson.build
yaml/xyz/openbmc_project/Control/SyncBMCData.errors.yaml
yaml/xyz/openbmc_project/Control/SyncBMCData.interface.yaml

- Introduced the "SiblingBMCNotAvailable" and "FullSyncInProgress" error code specific to SyncBMCData interfaces.
- Introduced the "StartFullSync" method interface to initiate a full sync of the configured files and directory to the sibling BMC.
- Introduced the "DisableSync" and "FullSyncStatus" property and Enum to define the Full Synchronization status of the BMC.
This PR is on top of [Rebase](https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/166) effort.
Included patches: [patch1](https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/76289), [patch2](https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/77378/6), [patch3](https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/77379/7), [patch4](https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-i …

SyncBMCData: Added interface, error code, method, property and enum 

---

yaml/xyz/openbmc_project/Control/SyncBMCData.errors.yaml
yaml/xyz/openbmc_project/Control/SyncBMCData.interface.yaml

- Introduced the 'SyncDisabled' error code specific to SyncBMCData interfaces.
- This error is triggered when a sync request is made while syncing is disabled.
- The 'StartFullSync' method now throws the following exception 
- xyz.openbmc_project.Control.SyncBMCData.Error.SyncDisabled
- Triggered when sync is disabled.
This PR includes upstream [patch](https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/78497/2). 
Change-Id: Ib3e787a4ee4768305ef0dbfab547107f9d6ba729
Signed-off-by: Harsh Agarwal <Harsh.Agarwal@ibm.com>

SyncBMCData: Added 'SyncDisabled' error code

---

yaml/xyz/openbmc_project/Control/SyncBMCData.interface.yaml

- This property helps monitor the current overall health of background sync events.
- This property can take values: "Ok", "Paused" and "Critical".
This PR includes upstream [patch](https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/78850).
Signed-off-by: Harsh Agarwal <Harsh.Agarwal@ibm.com>
Change-Id: Id3e2f868bb6cd0b2d135c48d250eee2cbb3e70e7

SyncBMCData: Added the "SyncEventsHealth" property and Enum

---

yaml/com/ibm/VPD.errors.yaml

```
* Update VPD.errors.yaml
Addition of Firmware error to populate com.ibm.VPD.Error.FirmwareError, the same will be used to log PEL in case any standard runtime exception is thrown by VPD Manager firmware code.
* Update VPD.errors.yaml```

1120: Update VPD.errors.yaml (#172)

---

gen/xyz/openbmc_project/Control/Failover/meson.build
gen/xyz/openbmc_project/Control/meson.build
yaml/xyz/openbmc_project/Control/Failover.interface.yaml

Create an interface to start a failover.  The first use will be to failover to another BMC, though the intent is the interface can also be used for other sorts of failovers.
Change-Id: I32789f6b8f01d1baed95d387e6815a797d5b45b8

Control: Add Failover interface
